### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by elia-ashraf** [jvcss/PyInstallerStreamlit#1]
Hi,

thank you so much for the tutorial. Everything had worked fine initially but when I try to open my .exe file, I get an error of a library (called rpyc) not being installed. Do you know what I can to solve the error?

`ModuleNotFoundError: No module named 'rpyc'`

Thank you.

**Comment by jvcss** [comment]
It's something about your Python version. Please provide details about your env, such as python version, streamlit version and which env is using

**Comment by elia-ashraf** [comment]
Hi, thank you for your reply. I figured out that any library that needs to be imported should be given under 
hidden_imports = ['...'] 
in the specs file.
