### ISSUE TITLE
How to Add Other Packages?

### ISSUE THREAD

**Issue by bitscoper** [jvcss/PyInstallerStreamlit#2]
Hello,
I followed your instructions, and it worked.

Now, I want to add YOLOv8 from Ultralytics, and CV2 (OpenCV-Python) to it.
So, what should I do (add or change) in the `.spec` file?

I tried adding them all like
```
datas=[
('./{MY_VIRTUAL_ENVIRONMENT}/lib/python3.11/site-packages/', '.'),
('./{MY_VIRTUAL_ENVIRONMENT}/lib64/python3.11/site-packages/', '.')
]
```

Still, some other packages or files are missing. _I think what I did was stupid._

Please help.

**Comment by jvcss** [comment]
Hello, as you can see in the example in the run_app.spec
```
datas=[
        (".env/Lib/site-packages/altair/vegalite/v4/schema/vega-lite-schema.json","./altair/vegalite/v4/schema/"),
        (".env/Lib/site-packages/streamlit/static","./streamlit/static"),
        (".env/Lib/site-packages/streamlit/runtime","./streamlit/runtime"),
    ],
```

To add more packages or files, you can follow a similar pattern and include them as tuples in the datas list. Each tuple consists of two elements: the source file/directory path and the destination path relative to the executable.
