### ISSUE TITLE
Log file for the .exe

### ISSUE THREAD

**Issue by elia-ashraf** [jvcss/PyInstallerStreamlit#4]
Hi,

This is not really an issue but a question.

How can I create a log file for this executable? Sometimes the .exe file does not run and shows an error but the error-window appears for a couple of seconds, which barely gives the user the time to read it. This is why I wanted to create a log file to output any such error(s). 

I have looked for solutions but those were not really helpful.

Thank you.

**Comment by jvcss** [comment]
You can add this in your main function that call the actual app. wrapp the call to your app with a try catch and place your log logic.
