### ISSUE TITLE
No module named streamlit.web error

### ISSUE THREAD

**Issue by punithnayak** [jvcss/PyInstallerStreamlit#5]
![image](https://github.com/jvcss/PyInstallerStreamlit/assets/110713318/0871fd7e-b83e-4d7b-af9e-050f367c2007)
I followedall the steps and i am getting this error

**Comment by jvcss** [comment]
please provide:
- streamlit version
- python version

recommended steps to make a successful build:
- clone the repository locally
- follow the step by step to generate the files
- make sure you are using a virtual environment and the **name of the environment folder starts with a dot** '.env' / '.envir'
- check if the version of streamlit you are using have this folder
- check if you correctly refering to the web folder

[watch this video](https://youtu.be/rMvrmBJmahE)


this error you are showing is common when your environment isn't starting with a dot so run `python -m venv .myenv` to create a valid environment. 
Other possible cause is that your IDE isn't recognizing the environment at all. So you should activate it first.

**Comment by jvcss** [comment]
this is not an issue with the project itself. closing.
