### ISSUE TITLE
delete app.py file 

### ISSUE THREAD

**Issue by bilaleknc** [jvcss/PyInstallerStreamlit#7]
Hello, isn't our goal to create an executable file and not need python files? But when I delete app.py before running the exe file I created, it gives an error

**Comment by jvcss** [comment]
actually the goal is to run the app from an exe

**Comment by jvcss** [comment]
but you can put the whole code inside the run_app.py too

**Comment by jvcss** [comment]
I did it like that because someone asked how can he run a multi file application
