### ISSUE TITLE
Not functioning in mac

### ISSUE THREAD

**Issue by martinpico** [jvcss/PyInstallerStreamlit#8]
I am unable to make this tutorial work on macos sonoma 14.3 with python 3.10.4 and streamlit 1.37.1. 

Just for your notice:

This block does not work in macos:

```
a = Analysis(
    ...
    datas=[
        (".env/Lib/site-packages/altair/vegalite/v5/schema/vega-lite-schema.json",
        "./altair/vegalite/v5/schema/"),
        (".env/Lib/site-packages/streamlit/static",
        "./streamlit/static"),
        (".env/Lib/site-packages/streamlit/runtime",
        "./streamlit/runtime"),
    ]
    ...
)
...
```

That is because using virtualenv the `Lib` directory is `lib`, and the libraries are inside a `python3.10` folder. I already changed this based on your implementation. 

The error I am getting is a common one, I think. My browser opens localhost3000 and there is nothing there. I also see a big thread of warnings and error that seem to inform that the program is not finding the app.py in the output directory.

**Comment by jvcss** [comment]
mac is not supported by this repository, I don't own a mac so I can't help. This repository if for generate Windows Executable.
